### ISSUE TITLE
document iv usage for aes

### ISSUE THREAD

**Issue by gotjoshua** [fission-suite/keystore-idb#70]
# Summary
I am trying to use the aes encrypt and decrypt functions and i can't quite grok whats up with the iv param

## Problem
when i derive my shared key using ECDH with my own private and public keys i can successfully decrypt, but if i derive a shared key with another users public key, the decryption fails.

I narrowed it down to 2 possiblities
1. i am doing something stupid (not "subtle" enough) with derivation and or padding or non padding
2. something is fishy with the way keystore is dealing with iv

so, is it "customary" to [tack the iv to the beginning of the encrypted payload](https://github.com/fission-codes/keystore-idb/blob/0bbb92aeba7a33a5372bd2ef64dce1c3ee1f7213/src/aes/operations.ts#L38)? 
...seems a bit shady, or?

so, i am sure that this is a request for documentation and strategy explanation, and i am not sure if may also be a bug.

Thanks!

**Comment by expede** [comment]
I can answer your IV question:

> so, is it "customary" to [tack the iv to the beginning of the encrypted payload](https://github.com/fission-codes/keystore-idb/blob/0bbb92aeba7a33a5372bd2ef64dce1c3ee1f7213/src/aes/operations.ts#L38)?

I also had this reaction when I learned about this stuff, but it's totally normal to do so. The IV is allowed to be public, and is commonly concatenated with the ciphertext (i.e. is kept on the "outside" in plain veiw). It's there to guard against certain attacks by adding entropy to the exact payload being encrypted, but you need it to decrypt correctly. However, it's not part of the encryption key's security and is safe to share widely (it's effectively a salt).

Here's some resources that I pulled up where you can get some more detail if interested:
- https://stackoverflow.com/questions/5796954/secret-vs-non-secret-initialization-vector#5797231
- https://www.baeldung.com/cs/security-key-vs-vector-vs-nonce#initialization-vectors

I hope that helps :)

**Comment by gotjoshua** [comment]
many thanks @expede !
i ended up using a stable iv from the tail end of the ipns name string, but that didn't end up being the problem.
your explanation and links definitely helped to calm my nerves about the iv strategy.

Eventually i discovered that my code for ecdh and aes was totally fine, i just had some stale key data in idb somewhere that was messing stuff up. Learned a lot debugging along the way.

Side note, i would love to try out awake but didn't find any ready made typescript code, and don't quite grok it solid enough to roll my own from the spec.

thanks !

**Comment by expede** [comment]
> don't quite grok it solid enough to roll my own from the spec.

We're about to replace big parts of the spec with [MLS](messaginglayersecurity.rocks/) (but still with UCAN at the auth layer), so probably good to hold off anyways :)

**Comment by expede** [comment]
Perhaps worth noting that in general using a random IV per ciphertext is recommended in case you reuse a key
